{% set org = "fishtown-analytics" %}
{% set name = "dbt" %}
{% set version = "0.19.2" %}
{% set sha256 = "9388d7a7f573c04bcad9274633aad277e4f05252e7d572c439e9dd90ae8f2980" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed . ./core ./plugins/postgres ./plugins/bigquery ./plugins/redshift ./plugins/snowflake

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  imports:
    - dbt
    - test

about:
  home: https://github.com/fishtown-analytics/dbt
  license: Apache-2.0
  license_file: License.md
  summary: dbt helps analysts write reliable, modular code using a workflow that closely mirrors software development.

  description: |
    dbt (data build tool) helps analysts write reliable, modular code
    using a workflow that closely mirrors software development. Used
    by individuals and teams alike, dbt is an analytics tool for
    perfectionists with deadlines.
  doc_url: http://dbt.readthedocs.io/en/master/
  dev_url: https://github.com/fishtown-analytics/dbt

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
    - thewchan
