{% set org = "fishtown-analytics" %}
{% set name = "dbt" %}
{% set version = "0.18.1" %}
{% set sha256 = "4d472ec6772c56863289063ba77cdc8806b244634c0c4ecbebe58858647b200b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install -r editable_requirements.txt

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - dbt
    - test

about:
  home: https://github.com/fishtown-analytics/dbt
  license: Apache-2.0
  license_file: License.md
  summary: dbt helps analysts write reliable, modular code using a workflow that closely mirrors software development.

  description: |
    dbt (data build tool) helps analysts write reliable, modular code
    using a workflow that closely mirrors software development. Used
    by individuals and teams alike, dbt is an analytics tool for
    perfectionists with deadlines.
  doc_url: http://dbt.readthedocs.io/en/master/
  dev_url: https://github.com/fishtown-analytics/dbt

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
