{% set version = "1.5.2" %}

package:
  name: dbt
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/d/dbt-core/dbt-core-{{ version }}.tar.gz
    sha256: e206563dd591f94573e56b19818d5cd87c462b1f1ad8f34eb88a2761bcc25b25
    folder: dbt-core
  - url: https://pypi.io/packages/source/d/dbt-postgres/dbt-postgres-{{ version }}.tar.gz
    sha256: a832f9d457eb91edc5d2ee3f1551d44db7e01aab41244f7fdb94e47ce4998f3a
    folder: dbt-postgres

build:
  number: 0
  noarch: python

outputs:
  - name: dbt-core
    build:
      noarch: python
      entry_points:
        - dbt = dbt.cli.main:cli
      script: python -m pip install --no-deps  -vv ./dbt-core
    requirements:
      host:
        - pip
        - python >=3.7.2
      run:
        - python >=3.7.2

        # Mashumaro is installed as "mashumaro[msgpack]", so the following comes from
        # the "extras_require" section of https://github.com/Fatal1ty/mashumaro/blob/master/setup.py
        - msgpack-python >=0.5.6

        # Generated with Grayskull v1.8.3
        # (Note: delete selector on networkx)
        - jinja2 ==3.1.2
        - agate >=1.6,<1.7.1
        - click >=7.0,<9
        - colorama >=0.3.9,<0.4.7
        - hologram >=0.0.14,<=0.0.16
        - isodate >=0.6,<0.7
        - logbook >=1.5,<1.6
        - mashumaro ==3.6
        - minimal-snowplow-tracker ==0.0.2
        - networkx >=2.3,<2.8.1
        - packaging >20.9
        - sqlparse >=0.2.3,<0.4.4
        - dbt-extractor >=0.4.1,<0.5.dev0
        - typing-extensions >=3.7.4
        - werkzeug >=1,<3
        - pathspec >=0.9,<0.12
        - protobuf >=4.0.0
        - pytz >=2015.7
        - requests <3.0.0
        - idna >=2.5,<4
        - cffi >=1.9,<2.0.0
        - pyyaml >=6.0
    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
        - dbt --help
      requires:
        - pip


  - name: dbt-postgres
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./dbt-postgres
    requirements:
      host:
        - pip
        - python >=3.7
      run:
        - python >=3.7
        - {{ pin_subpackage("dbt-core", exact=True) }}
        # Generated with Grayskull v1.8.3
        - psycopg2-binary >=2.8,<3.dev0
    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/dbt-labs/dbt
  summary: With dbt, data analysts and engineers can build analytics the way engineers build applications.
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
    - maresb
    - thewchan
