{% set org = "dbt-labs" %}
{% set name = "dbt-core" %}
{% set version = "0.21.0" %}
{% set sha256 = "5a9c00aca61c5252af9ece51c8b56fab835d1c880b88f6af857935d43dea272d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed . ./core ./plugins/postgres ./plugins/bigquery ./plugins/redshift ./plugins/snowflake

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    # https://github.com/dbt-labs/dbt-core/blob/v0.21.0/core/setup.py
    - jinja2 ==2.11.3
    - pyyaml >=3.11
    - agate >=1.6,<1.6.2
    - colorama >=0.3.9,<0.4.5
    - dataclasses >=0.6,<0.9
    - hologram ==0.0.14
    - isodate >=0.6,<0.7
    - json-rpc >=1.12,<2
    - logbook >=1.5,<1.6
    - mashumaro ==2.5
    - minimal-snowplow-tracker ==0.0.2
    - networkx >=2.3,<3
    - packaging >=20.9,<20.10
    - sqlparse >=0.2.3,<0.5
    - dbt-extractor ==0.4.0
    - typing-extensions >=3.7.4,<3.11
    - werkzeug >=1,<3

test:
  imports:
    - dbt
    - test
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dbt-labs/dbt-core
  license: Apache-2.0
  license_file: License.md
  summary: dbt helps analysts write reliable, modular code using a workflow that closely mirrors software development.

  description: |
    dbt (data build tool) helps analysts write reliable, modular code
    using a workflow that closely mirrors software development. Used
    by individuals and teams alike, dbt is an analytics tool for
    perfectionists with deadlines.
  doc_url: http://dbt.readthedocs.io/en/master/
  dev_url: https://github.com/dbt-labs/dbt-core

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
    - thewchan
