{% set version = "1.7.2" %}

package:
  name: dbt
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/d/dbt-core/dbt-core-{{ version }}.tar.gz
    sha256: ec0a06a5015a830f63ad3fd506473cbf12edafeae89cf2d611a10836788da603
    folder: dbt-core
  - url: https://pypi.io/packages/source/d/dbt-postgres/dbt-postgres-{{ version }}.tar.gz
    sha256: 11d3822eec1d62ad70eb7497b41fb86bfd44bcb8d8b449d6dc35f9bd5cfa8982
    folder: dbt-postgres

build:
  number: 0
  noarch: python

outputs:
  - name: dbt-core
    build:
      noarch: python
      entry_points:
        - dbt = dbt.cli.main:cli
      script: python -m pip install --no-deps  -vv ./dbt-core
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - python >=3.8

        # Mashumaro is installed as "mashumaro[msgpack]", so the following comes from
        # the "extras_require" section of https://github.com/Fatal1ty/mashumaro/blob/master/setup.py
        - msgpack-python >=0.5.6

        # Generated with Grayskull
        - agate >=1.7.0,<1.8.dev0
        - jinja2 >=3.1.2,<3.2.dev0
        - mashumaro >=3.8.1,<3.9.dev0
        - logbook >=1.5,<1.6
        - click <9
        - networkx >=2.3,<4
        - colorama >=0.3.9,<0.5
        - pathspec >=0.9,<0.12
        - isodate >=0.6,<0.7
        - sqlparse >=0.2.3,<0.5
        - dbt-extractor >=0.4.1,<0.5.dev0
        - hologram >=0.0.16,<0.1.dev0
        - minimal-snowplow-tracker >=0.0.2,<0.1.dev0
        - dbt-semantic-interfaces >=0.2.0,<0.3.dev0
        - packaging >20.9
        - protobuf >=4.0.0
        - pytz >=2015.7
        - pyyaml >=6.0
        - typing-extensions >=3.7.4
        - cffi >=1.9,<2.0.0
        - idna >=2.5,<4
        - requests <3.0.0
        - urllib3 >=1.0,<2.dev0
    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
        - dbt --help
      requires:
        - pip


  - name: dbt-postgres
    build:
      noarch: python
      script: python -m pip install --no-deps -vv ./dbt-postgres
    requirements:
      host:
        - pip
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage("dbt-core", exact=True) }}
        # Generated with Grayskull
        - psycopg2-binary >=2.8,<3.dev0
        - agate
    test:
      imports:
        - dbt
        - dbt.adapters
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/dbt-labs/dbt
  summary: With dbt, data analysts and engineers can build analytics the way engineers build applications.
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - drewbanin
    - jthandy
    - maresb
    - thewchan
